name: build-bin

on:
  push:
    branches:
      - 'main'


jobs:
  bin:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go 1.20.5
      uses: actions/setup-go@v1
      with: 
        go-version: 1.20.5         

    - name: Build app 
      run: go build -o app main.go

    - name: SCP to AWS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        source: "app"         
        target: "app"

  deploy:
    needs: bin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu
          command: fuser -k 8080/tcp && ./app/app & disown
          comment: Pull and run container

      # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"